//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reitit.Strings.en_US {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OldResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OldResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reitit.Strings.en_US.OldResources", typeof(OldResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aerial mode off.
        /// </summary>
        internal static string AerialOffText {
            get {
                return ResourceManager.GetString("AerialOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aerial mode on.
        /// </summary>
        internal static string AerialOnText {
            get {
                return ResourceManager.GetString("AerialOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REITIT.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE DATE.
        /// </summary>
        internal static string DatePickerTitle {
            get {
                return ResourceManager.GetString("DatePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lines.
        /// </summary>
        internal static string ListLinesHeader {
            get {
                return ResourceManager.GetString("ListLinesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorites.
        /// </summary>
        internal static string LocationPickerAddFavText {
            get {
                return ResourceManager.GetString("LocationPickerAddFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addresses.
        /// </summary>
        internal static string LocationPickerAddressesHeader {
            get {
                return ResourceManager.GetString("LocationPickerAddressesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string LocationPickerCancelText {
            get {
                return ResourceManager.GetString("LocationPickerCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use a contact&apos;s address.
        /// </summary>
        internal static string LocationPickerChooseAddressText {
            get {
                return ResourceManager.GetString("LocationPickerChooseAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string LocationPickerDoneText {
            get {
                return ResourceManager.GetString("LocationPickerDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use my location.
        /// </summary>
        internal static string LocationPickerMeText {
            get {
                return ResourceManager.GetString("LocationPickerMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a match. Try a different spelling or search for another location..
        /// </summary>
        internal static string LocationPickerNoResults {
            get {
                return ResourceManager.GetString("LocationPickerNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string LocationPickerOtherHeader {
            get {
                return ResourceManager.GetString("LocationPickerOtherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places.
        /// </summary>
        internal static string LocationPickerPlacesHeader {
            get {
                return ResourceManager.GetString("LocationPickerPlacesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured when trying to retrieve the results for your search. Try again or contact the app creator if the problem persists..
        /// </summary>
        internal static string LocationPickerSearchFailed {
            get {
                return ResourceManager.GetString("LocationPickerSearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve locations.
        /// </summary>
        internal static string LocationPickerSearchFailedTitle {
            get {
                return ResourceManager.GetString("LocationPickerSearchFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for places and addresses.
        /// </summary>
        internal static string LocationPickerSearchHint {
            get {
                return ResourceManager.GetString("LocationPickerSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type at least 3 characters..
        /// </summary>
        internal static string LocationPickerShortSearchPrompt {
            get {
                return ResourceManager.GetString("LocationPickerShortSearchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term too short.
        /// </summary>
        internal static string LocationPickerShortSearchPromptTitle {
            get {
                return ResourceManager.GetString("LocationPickerShortSearchPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stops.
        /// </summary>
        internal static string LocationPickerStopsHeader {
            get {
                return ResourceManager.GetString("LocationPickerStopsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE LOCATION.
        /// </summary>
        internal static string LocationPickerTitle {
            get {
                return ResourceManager.GetString("LocationPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From map.
        /// </summary>
        internal static string MapLocationPlaceholderText {
            get {
                return ResourceManager.GetString("MapLocationPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My location.
        /// </summary>
        internal static string MyLocationText {
            get {
                return ResourceManager.GetString("MyLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure flight mode is turned off and check your mobile data or Wifi connection..
        /// </summary>
        internal static string NetworkUnavailableText {
            get {
                return ResourceManager.GetString("NetworkUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the Internet.
        /// </summary>
        internal static string NetworkUnavailableTitle {
            get {
                return ResourceManager.GetString("NetworkUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        internal static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route.
        /// </summary>
        internal static string RouteButtonText {
            get {
                return ResourceManager.GetString("RouteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Wait &apos;h&apos; hours &apos;m&apos; minutes&apos;.
        /// </summary>
        internal static string RouteControlHoursWaitFormat {
            get {
                return ResourceManager.GetString("RouteControlHoursWaitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Wait &apos;m&apos; minutes&apos;.
        /// </summary>
        internal static string RouteControlMinutesWaitFormat {
            get {
                return ResourceManager.GetString("RouteControlMinutesWaitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string RouteLoaderLoadingStatus {
            get {
                return ResourceManager.GetString("RouteLoaderLoadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting your location.
        /// </summary>
        internal static string RouteLoaderLocatingStatus {
            get {
                return ResourceManager.GetString("RouteLoaderLocatingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advanced.
        /// </summary>
        internal static string RouteSearchAdvanced {
            get {
                return ResourceManager.GetString("RouteSearchAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string RouteSearchButtonText {
            get {
                return ResourceManager.GetString("RouteSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string RouteSearchFromHeader {
            get {
                return ResourceManager.GetString("RouteSearchFromHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer margin.
        /// </summary>
        internal static string RouteSearchMarginHeader {
            get {
                return ResourceManager.GetString("RouteSearchMarginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes of transport used.
        /// </summary>
        internal static string RouteSearchModesHeader {
            get {
                return ResourceManager.GetString("RouteSearchModesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string RouteSearchOverlayText {
            get {
                return ResourceManager.GetString("RouteSearchOverlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking speed.
        /// </summary>
        internal static string RouteSearchSpeedHeader {
            get {
                return ResourceManager.GetString("RouteSearchSpeedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string RouteSearchTimeHeader {
            get {
                return ResourceManager.GetString("RouteSearchTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND ROUTES.
        /// </summary>
        internal static string RouteSearchTitle {
            get {
                return ResourceManager.GetString("RouteSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string RouteSearchToHeader {
            get {
                return ResourceManager.GetString("RouteSearchToHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route type.
        /// </summary>
        internal static string RouteSearchTypeHeader {
            get {
                return ResourceManager.GetString("RouteSearchTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string RoutesInitialLoading {
            get {
                return ResourceManager.GetString("RoutesInitialLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a match. Check that your route waypoints are within the Helsinki area or try altering your search parameters..
        /// </summary>
        internal static string RoutesNoRoutesText {
            get {
                return ResourceManager.GetString("RoutesNoRoutesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROUTES.
        /// </summary>
        internal static string RoutesTitle {
            get {
                return ResourceManager.GetString("RoutesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  TO .
        /// </summary>
        internal static string RoutesTitleSeparator {
            get {
                return ResourceManager.GetString("RoutesTitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string RouteTypeDefault {
            get {
                return ResourceManager.GetString("RouteTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fastest.
        /// </summary>
        internal static string RouteTypeFastest {
            get {
                return ResourceManager.GetString("RouteTypeFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to least transfers.
        /// </summary>
        internal static string RouteTypeTransfers {
            get {
                return ResourceManager.GetString("RouteTypeTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to least walking.
        /// </summary>
        internal static string RouteTypeWalking {
            get {
                return ResourceManager.GetString("RouteTypeWalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured when trying to retrieve the results for your search. Try again or contact the app creator if the problem persists..
        /// </summary>
        internal static string SearchFailed {
            get {
                return ResourceManager.GetString("SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve search results.
        /// </summary>
        internal static string SearchFailedTitle {
            get {
                return ResourceManager.GetString("SearchFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for lines, places and addresses.
        /// </summary>
        internal static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string SearchingStatus {
            get {
                return ResourceManager.GetString("SearchingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a match. Try a different spelling or change your search term..
        /// </summary>
        internal static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        internal static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE TIME.
        /// </summary>
        internal static string TimePickerTitle {
            get {
                return ResourceManager.GetString("TimePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrive at.
        /// </summary>
        internal static string TimeTypeArriveAt {
            get {
                return ResourceManager.GetString("TimeTypeArriveAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depart at.
        /// </summary>
        internal static string TimeTypeDepartAt {
            get {
                return ResourceManager.GetString("TimeTypeDepartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        internal static string TimeTypeNow {
            get {
                return ResourceManager.GetString("TimeTypeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cycling 300 m/min.
        /// </summary>
        internal static string WalkSpeedCycling {
            get {
                return ResourceManager.GetString("WalkSpeedCycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default 70 m/min.
        /// </summary>
        internal static string WalkSpeedDefault {
            get {
                return ResourceManager.GetString("WalkSpeedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fast 100 m/min.
        /// </summary>
        internal static string WalkSpeedFast {
            get {
                return ResourceManager.GetString("WalkSpeedFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running 200 m/min.
        /// </summary>
        internal static string WalkSpeedRunning {
            get {
                return ResourceManager.GetString("WalkSpeedRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slow 30 m/min.
        /// </summary>
        internal static string WalkSpeedSlow {
            get {
                return ResourceManager.GetString("WalkSpeedSlow", resourceCulture);
            }
        }
    }
}
