//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reitit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reitit.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aerial mode off.
        /// </summary>
        public static string AerialOffText {
            get {
                return ResourceManager.GetString("AerialOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aerial mode on.
        /// </summary>
        public static string AerialOnText {
            get {
                return ResourceManager.GetString("AerialOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REITIT.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE DATE.
        /// </summary>
        public static string DatePickerTitle {
            get {
                return ResourceManager.GetString("DatePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a match. Try a different spelling or search for a nearby location..
        /// </summary>
        public static string LocationPickerNoResults {
            get {
                return ResourceManager.GetString("LocationPickerNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for places and addresses.
        /// </summary>
        public static string LocationPickerSearchHint {
            get {
                return ResourceManager.GetString("LocationPickerSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE LOCATION.
        /// </summary>
        public static string LocationPickerTitle {
            get {
                return ResourceManager.GetString("LocationPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From map.
        /// </summary>
        public static string MapLocationPlaceholderText {
            get {
                return ResourceManager.GetString("MapLocationPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My location.
        /// </summary>
        public static string MyLocationText {
            get {
                return ResourceManager.GetString("MyLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string PickerCancelText {
            get {
                return ResourceManager.GetString("PickerCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string PickerDoneText {
            get {
                return ResourceManager.GetString("PickerDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route.
        /// </summary>
        public static string RouteButtonText {
            get {
                return ResourceManager.GetString("RouteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string RouteSearchButtonText {
            get {
                return ResourceManager.GetString("RouteSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string RouteSearchFromHeader {
            get {
                return ResourceManager.GetString("RouteSearchFromHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer margin.
        /// </summary>
        public static string RouteSearchMarginHeader {
            get {
                return ResourceManager.GetString("RouteSearchMarginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes of transport used.
        /// </summary>
        public static string RouteSearchModesHeader {
            get {
                return ResourceManager.GetString("RouteSearchModesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking speed.
        /// </summary>
        public static string RouteSearchSpeedHeader {
            get {
                return ResourceManager.GetString("RouteSearchSpeedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string RouteSearchTimeHeader {
            get {
                return ResourceManager.GetString("RouteSearchTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND ROUTES.
        /// </summary>
        public static string RouteSearchTitle {
            get {
                return ResourceManager.GetString("RouteSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string RouteSearchToHeader {
            get {
                return ResourceManager.GetString("RouteSearchToHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route type.
        /// </summary>
        public static string RouteSearchTypeHeader {
            get {
                return ResourceManager.GetString("RouteSearchTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string RouteTypeDefault {
            get {
                return ResourceManager.GetString("RouteTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fastest.
        /// </summary>
        public static string RouteTypeFastest {
            get {
                return ResourceManager.GetString("RouteTypeFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to least transfers.
        /// </summary>
        public static string RouteTypeTransfers {
            get {
                return ResourceManager.GetString("RouteTypeTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to least walking.
        /// </summary>
        public static string RouteTypeWalking {
            get {
                return ResourceManager.GetString("RouteTypeWalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE TIME.
        /// </summary>
        public static string TimePickerTitle {
            get {
                return ResourceManager.GetString("TimePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrive at.
        /// </summary>
        public static string TimeTypeArriveAt {
            get {
                return ResourceManager.GetString("TimeTypeArriveAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depart at.
        /// </summary>
        public static string TimeTypeDepartAt {
            get {
                return ResourceManager.GetString("TimeTypeDepartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string TimeTypeNow {
            get {
                return ResourceManager.GetString("TimeTypeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cycling 300 m/min.
        /// </summary>
        public static string WalkSpeedCycling {
            get {
                return ResourceManager.GetString("WalkSpeedCycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default 70 m/min.
        /// </summary>
        public static string WalkSpeedDefault {
            get {
                return ResourceManager.GetString("WalkSpeedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fast 100 m/min.
        /// </summary>
        public static string WalkSpeedFast {
            get {
                return ResourceManager.GetString("WalkSpeedFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running 200 m/min.
        /// </summary>
        public static string WalkSpeedRunning {
            get {
                return ResourceManager.GetString("WalkSpeedRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slow 30 m/min.
        /// </summary>
        public static string WalkSpeedSlow {
            get {
                return ResourceManager.GetString("WalkSpeedSlow", resourceCulture);
            }
        }
    }
}
